version: "3.8"

services:
  # Servicio de la Base de Datos (MariaDB)
  mariadb:
    image: mariadb:10.11
    container_name: castilfac_db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - castilfac_db_data:/var/lib/mysql

  # Servicio del Backend (Node.js)
  backend:
    build: .
    container_name: castilfac_api
    restart: always
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mariadb
    environment:
      - PORT=${PORT}
      - DB_HOST=mariadb # Nombre del servicio de arriba
      - DB_PORT=3306
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - REFRESH_SECRET_KEY=${REFRESH_SECRET_KEY}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - URL=${URL}
      - FRONTEND_URL=${FRONTEND_URL}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}

volumes:
  castilfac_db_data:
